Parameters:
  BucketName:
    Type: String
    Default: ''

  BotBucketName:
    Type: String
    Default: ''

  BotExport:
    Type: String
    Default: ''

  
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LexBotV2:
    Type: 'AWS::Lex::Bot'
    Properties:
      Name: MyLexBot
      Description: Elliott's Amazon Lex V2 Bot Lab
      RoleArn: !GetAtt LexBotRole.Arn
      IdleSessionTTLInSeconds: 300
      BotLocales: 
        - BotLocale
      BotFileS3Location: 
        S3Bucket: !Ref BotBucketName
        S3ObjectKey: !Ref BotExport
      DataPrivacy:
        ChildDirected: false
  LexBotRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: LexBotRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lexv2.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LexBotPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lexv2:CreateBot'
                  - 'lexv2:DeleteBot'
                  - 'lexv2:DescribeBot'
                  - 'lexv2:UpdateBot'
                  - 'lexv2:CreateBotAlias'
                  - 'lexv2:DeleteBotAlias'
                  - 'lexv2:DescribeBotAlias'
                  - 'lexv2:UpdateBotAlias'
                  - 'lexv2:CreateBotLocale'
                  - 'lexv2:DeleteBotLocale'
                  - 'lexv2:DescribeBotLocale'
                  - 'lexv2:UpdateBotLocale'
                  - 'lexv2:CreateIntent'
                  - 'lexv2:DeleteIntent'
                  - 'lexv2:DescribeIntent'
                  - 'lexv2:UpdateIntent'
                  - 'lexv2:CreateSlot'
                  - 'lexv2:DeleteSlot'
                  - 'lexv2:DescribeSlot'
                  - 'lexv2:UpdateSlot'
                Resource: '*'
  LexBotAlarm1:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: MissedUtteranceCountAlarm
      AlarmDescription: 'Alarm for MissedUtteranceCount metric'
      Namespace: 'AWS/Lex'
      MetricName: 'MissedUtteranceCount'
      Dimensions:
        - Name: 'BotName'
          Value: !Ref LexBotV2
        - Name: 'BotAlias'
          Value: 'LATEST'
      Statistic: 'Sum'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - !Ref SnsTopicArn
  LexBotAlarm2:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: IntentCountAlarm
      AlarmDescription: 'Alarm for IntentCount metric'
      Namespace: 'AWS/Lex'
      MetricName: 'IntentCount'
      Dimensions:
        - Name: 'BotName'
          Value: !Ref LexBotV2
        - Name: 'BotAlias'
          Value: 'LATEST'
      Statistic: 'Sum'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - !Ref SnsTopicArn
  LexBotAlarm3:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: FulfilledRequestCountAlarm
      AlarmDescription: 'Alarm for FulfilledRequestCount metric'
      Namespace: 'AWS/Lex'
      MetricName: 'FulfilledRequestCount'
      Dimensions:
        - Name: 'BotName'
          Value: !Ref LexBotV2
        - Name: 'BotAlias'
          Value: 'LATEST'
      Statistic: 'Sum'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - !Ref SnsTopicArn
  LexBotAlarm4:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: PositiveFeedbackCountAlarm
      AlarmDescription: 'Alarm for PositiveFeedbackCount metric'
      Namespace: 'AWS/Lex'
      MetricName: 'PositiveFeedbackCount'
      Dimensions:
        - Name: 'BotName'
          Value: !Ref LexBotV2
        - Name: 'BotAlias'
          Value: 'LATEST'
      Statistic: 'Sum'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - !Ref SnsTopicArn
  LexBotAlarm5:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: NegativeFeedbackCountAlarm
      AlarmDescription: 'Alarm for NegativeFeedbackCount metric'
      Namespace: 'AWS/Lex'
      MetricName: 'NegativeFeedbackCount'
      Dimensions:
        - Name: 'BotName'
          Value: !Ref LexBotV2
        - Name: 'BotAlias'
          Value: 'LATEST'
      Statistic: 'Sum'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - !Ref SnsTopicArn
